 Question: 1 
 Given below is a dictionary having two keys ‘Boys’ and ‘Girls’ and having two lists of heights of five Boys and Five Girls respectively as values associated with these keys Original dictionary of lists: {'Boys': [72, 68, 70, 69, 74], 'Girls': [63, 65, 69, 62, 61]} From the given dictionary of lists create the following list of dictionaries: [{'Boys': 72, 'Girls': 63}, {'Boys': 68, 'Girls': 65}, {'Boys': 70, 'Girls': 69}, {'Boys': 69, 'Girls': 62}, {‘Boys’:74, ‘Girls’:61]

In [ ]:
original_dict={'Boys': [72, 68, 70, 69, 74], 'Girls': [63, 65, 69, 62, 61]}
list1=list()
for i in range(len(original_dict['Girls'])):
    dictionary=dict()
    dictionary['Boys']=original_dict['Boys'][i]
    dictionary['Girls']=original_dict['Girls'][i]
    list1.append(dictionary)

print(list1)

Question: 2 :
Given are three lists where L1 has names of n students, L2 has marks and L3 has hobbies of n students.Using three lists, create the following dictionary with hobbies as keys and (names,marks) as values. In case more than one student has same hobby then values must be appended for the same key instead of overwriting.E.g.
L1=['A','B','C']   L2=[100,40,50] L3=['painting','music','painting']  
then output should be:
dict1={painting:(('A',100),('C',50)), 'music':('B',40)}

In [ ]:
L1=['A','B','C']
L2=[100,40,50]
L3=['painting','music','painting']

dict1=dict()
for i in range(len(L3)):
    name=L1[i]
    marks=L2[i]
    hobby=L3[i]

    if hobby not in dict1:
        dict1[hobby]=[]

    dict1[hobby].append((name,marks))

for hobby,values in dict1.items():
        dict1[hobby]=tuple(values)

print(dict1)

Question-3
Write a lambda function to arrange a list of names on the last letter of the name then print the sorted list on last letter.

In [1]:
word_list = ["apple", "banana", "cherry", "date", "fig", "grape","orange"]

sorted_list = sorted(word_list, key=lambda word: word[-1])

print(sorted_list)

['banana', 'apple', 'date', 'grape', 'orange', 'fig', 'cherry']


Question-4: Make groups in a list of names on the basis of last name and store in a
dictionary using itertools


In [1]:
import itertools as it

names = [ "Julie Kapoor","Aryan Singh", "Vriddhi Singh", "Evanya Chopra", "Priyanka Chopra"]

name_groups = {}
for last_name, group in it.groupby(names, key=lambda name: name.split()[-1]):
    name_groups[last_name] = list(group)

print(name_groups)

{'Kapoor': ['Julie Kapoor'], 'Singh': ['Aryan Singh', 'Vriddhi Singh'], 'Chopra': ['Evanya Chopra', 'Priyanka Chopra']}


Question-5: Create a generator expression to X+X^2 for first 100 numbers

In [1]:
exp=(x+(x**2)for x in range(1,101))
for num in exp:
    print(num,end=" ")

2 6 12 20 30 42 56 72 90 110 132 156 182 210 240 272 306 342 380 420 462 506 552 600 650 702 756 812 870 930 992 1056 1122 1190 1260 1332 1406 1482 1560 1640 1722 1806 1892 1980 2070 2162 2256 2352 2450 2550 2652 2756 2862 2970 3080 3192 3306 3422 3540 3660 3782 3906 4032 4160 4290 4422 4556 4692 4830 4970 5112 5256 5402 5550 5700 5852 6006 6162 6320 6480 6642 6806 6972 7140 7310 7482 7656 7832 8010 8190 8372 8556 8742 8930 9120 9312 9506 9702 9900 10100 

Question -6 :  Write programs in Python using NumPy library to do the following:
 a. Compute the mean, standard deviation, and variance of a two dimensional random integer array along the second axis. 
 b. Get the indices of the sorted elements of a given array. B = [56, 48, 22, 41, 78, 91, 24, 46, 8, 33]
 c. Create a 2-dimensional array of size m x n integer elements, also print the shape, type and data type of the array and then reshape it into nx m array, n and m are user inputs given at the run time. 
 d. Test whether the elements of a given array are zero, non-zero and NaN. 
 Record the indices of these elements in three separate arrays.

In [6]:
!python -m pip install numpy


                                              0.0/15.5 MB ? eta -:--:--
                                              0.0/15.5 MB ? eta -:--:--
                                             0.0/15.5 MB 330.3 kB/s eta 0:00:47
                                             0.0/15.5 MB 330.3 kB/s eta 0:00:47
                                             0.0/15.5 MB 245.8 kB/s eta 0:01:04
                                             0.1/15.5 MB 353.1 kB/s eta 0:00:44
                                             0.1/15.5 MB 350.1 kB/s eta 0:00:45
                                             0.1/15.5 MB 344.8 kB/s eta 0:00:45
                                             0.1/15.5 MB 343.4 kB/s eta 0:00:45
                                             0.1/15.5 MB 370.8 kB/s eta 0:00:42
                                             0.2/15.5 MB 361.7 kB/s eta 0:00:43
                                             0.2/15.5 MB 361.7 kB/s eta 0:00:43
                                             0.2/15.5 MB

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [18]:
import numpy as np

array = np.random.randint(0, 10, size=(3, 5))

mean = np.mean(array, axis=1)
std_dev = np.std(array, axis=1)
variance = np.var(array, axis=1)


print("Original Array:")
print(array)
print("Mean along the second axis:")
print(mean)
print("Standard Deviation along the second axis:")
print(std_dev)
print("Variance along the second axis:")
print(variance)



Original Array:
[[0 4 9 3 4]
 [9 4 9 4 5]
 [3 1 3 0 0]]
Mean along the second axis:
[4.  6.2 1.4]
Standard Deviation along the second axis:
[2.89827535 2.31516738 1.356466  ]
Variance along the second axis:
[8.4  5.36 1.84]


In [5]:
B = np.array([56, 48, 22, 41, 78, 91, 24, 46, 8, 33])
sorted_indices = np.argsort(B)

print("Original Array:")
print(B)
print("Indices of Sorted Elements:")
print(sorted_indices)

Original Array:
[56 48 22 41 78 91 24 46  8 33]
Indices of Sorted Elements:
[8 2 6 9 3 7 1 0 4 5]


In [6]:
m = int(input("Enter the number of rows (m): "))
n = int(input("Enter the number of columns (n): "))

# Create a random m x n array of integers
array = np.random.randint(0, 100, size=(m, n))

print("Original Array:")
print(array)
print("Shape:", array.shape)
print("Type:", type(array))
print("Data Type:", array.dtype)

# Reshape it into an nxm array
reshaped_array = array.reshape(n, m)
print("Reshaped Array:")
print(reshaped_array)

Original Array:
[[92 86 66 25]
 [24  5 57 51]
 [66 61 31 12]]
Shape: (3, 4)
Type: <class 'numpy.ndarray'>
Data Type: int32
Reshaped Array:
[[92 86 66]
 [25 24  5]
 [57 51 66]
 [61 31 12]]


In [14]:

# Create a sample array with some zeros, non-zeros, and NaN values
array = np.array([1.0, 0.0, 2.0, 0.0, np.nan, 3.0])

# Test for zero elements and record their indices
zero_indices = np.where(array == 0.0)[0]

# Test for non-zero elements and record their indices
nonzero_indices = np.where(array != 0.0)[0]

# Test for NaN elements and record their indices
nan_indices = np.where(np.isnan(array))[0]

print("Original Array:")
print(array)
print("Indices of Zero Elements:")
print(zero_indices)
print("Indices of Non-Zero Elements:")
print(nonzero_indices)
print("Indices of NaN Elements:")
print(nan_indices)


Original Array:
[ 1.  0.  2.  0. nan  3.]
Indices of Zero Elements:
[1 3]
Indices of Non-Zero Elements:
[0 2 4 5]
Indices of NaN Elements:
[4]


Question-7: 
Generate a 2D array having values from 1 to 100 of shape (4,5).
I. Multiply all elements that are greater than 50 by 2 
II. Extract 2x2 lower-right matrix from the given array and find its largest element

In [16]:
array = np.random.randint(1,101 , size=(4, 5))
print("Original Array : ")
print(array)


# I. Multiply all elements greater than 50 by 2
indices = np.where(array > 50)
array[indices] *= 2

print("Array after Multiplication: ")
print(array)

Original Array : 
[[ 96  28  81  76   3]
 [ 11  40  20   4 100]
 [  5  12  62  43  27]
 [ 58  14  73  12  83]]
Array after Multiplication: 
[[192  28 162 152   3]
 [ 11  40  20   4 200]
 [  5  12 124  43  27]
 [116  14 146  12 166]]


In [17]:
# II. Extract the 2x2 lower-right matrix and find its largest element
lower_right_matrix = array[-2:, -2:]  # Extract the lower-right 2x2 matrix
largest_element = np.max(lower_right_matrix)

print("\nLower-Right 2x2 Matrix:")
print(lower_right_matrix)
print("\nLargest Element in Lower-Right Matrix:", largest_element)


Lower-Right 2x2 Matrix:
[[ 43  27]
 [ 12 166]]

Largest Element in Lower-Right Matrix: 166
